sonar.organization=femkevdbrom
sonar.projectKey=femkevdBrom_ScoutingApp

sonar.sources=backend/src/main/java,frontend/src
sonar.test=backend/src/tes/java
sonar.java.binaries=backend/build/classes
sonar.exclusions=frontend/node_modules/**,frontend/build/**