spring.application.name=backend
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
app:
    jwt:
        Secret:kuRDjuMHgkV5hM0LrgMr43UbhihRVaw0WINnQstu9xI
        expiration-ms: 3600000

spring.datasource.url=jdbc:postgresql://postgres:5432/scoutingappdb
spring.datasource.username=postgres
spring.datasource.password=DBf0r3v3rything
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

